name: CI-CD
on: [ push, pull_request ]

jobs:
  cicd:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Coursier cache
        uses: coursier/cache-action@v5

      - name: clean
        run: sbt clean

      - name: build
        run: sbt compile

      - name: plugin-test
        run: sbt '; set isSnapshot := true ; scripted'

      - name: unit-test-coverage
        run: sbt ";clean; coverage; test; coverageReport; coveralls"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release-staging
        run: sbt ";set isSnapshot := true ; clean ; ci-release"
        if: startsWith(github.ref, 'refs/tags/') != true && github.ref == 'refs/heads/main'
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

      - name: release-production
        run: sbt "; clean ; ci-release"
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

      - name: clean-up
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
